name: Tasks needing write permissions

on:
  workflow_call:

jobs:
  add-comment:
    if: github.event.workflow_run.name == 'Test deployment'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read
    steps:
      - name: Download artifact
        id: download-artifact
        continue-on-error: true
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: comment-artifact
          path: comment-artifact
      - name: Add a PR comment
        if: steps.download-artifact.conclusion == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(gh api /repos/${{ github.event.workflow_run.repository.full_name }}/commits/${{ github.event.workflow_run.head_sha }}/pulls --jq '.[0].number')
          gh pr comment $PR_NUMBER \
           --edit-last \
           --create-if-none \
           --body-file comment-artifact/body.txt \
           --repo ${{ github.event.workflow_run.repository.full_name }}
      